name: Run all unittests by vitest

on: push

jobs:
  js-vitest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front

    steps:
      - name: Source checkout
        uses: actions/checkout@v4
      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install node dependencies
        run: yarn install
      - name: Run all tests
        run: yarn test
